### ISSUE TITLE
T3.3.2 implementation: routing, aggregation, monitor, display

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#236]
It would be better to split this issue into few PRs:

1. Create `MEvPreCond`, optional precondition for monitoring (if it's defined, but returns `False`, monitoring expression will be ignored). _Use "count" value from stats?_.

2. Extend `action` to be able to define it as `CreateMessage "Warning" "Something is wrong with an epoch validation"`.

3. Add `Plus` and `Minus` in the parser, to be able to define a condition like: `ewma.avg > stats.mean + (2 seconds) || ewma.avg < stats.mean - (2 seconds))`.

**Comment by denisshevchenko** [comment]
If we want to be able to use different values in `monitor`-expression, for example:

```
monitMe > stats.mean > (2 seconds)
```

we have to get this value from `Environment`. But first we have to insert this value _into_ `Environment`. We can take the main value from the `LogObject` (in this case it's a value of `monitMe`), but `LogObject` can contain only _one_ observable value. So we have to take another one (the value of `stats.mean`) from the other place.

The idea is to take it from the `LogBuffer`, because `LogBuffer` contains all latest `LogObject`s from all backends.

@CodiePP said:

> the observables only enter LogBuffer if they are routed towards this. for some you might want to duplicate the trace (TeeTrace) first. I guess you then have to address them with the complete name
>
> `#buffered.#aggregation.some.value.of.importance.stats.fbasic.mean`

**Comment by denisshevchenko** [comment]
So, all three PRs are merged now.
