### ISSUE TITLE
T7.2.1 implementation: send metrics to Prometheus

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#242]
reqs in #239:

output metrics on EKG, and expose to Prometheus with http://hackage.haskell.org/package/ekg-prometheus-adapter
or directly push metrics to Prometheus with https://github.com/fimad/prometheus-haskell

**Comment by 365andreas** [comment]
http://hackage.haskell.org/package/ekg-prometheus-adapter-0.1.0.4 has not been updated to follow the changes in http://hackage.haskell.org/package/prometheus-2.1.1.
So a fork with a commit fixing the issue is located https://github.com/365andreas/ekg-prometheus-adapter/commit/2123420a37044c4f8910cbb0876620f8952970af.

**Comment by 365andreas** [comment]
[prometheus-2.1.1](http://hackage.haskell.org/package/prometheus-2.1.1) does not support [Labels](http://hackage.haskell.org/package/ekg-0.4.0.15/docs/System-Remote-Label.html#t:Label) in contrast with `EKG`. Consequently, it may be needed to change [Labels](http://hackage.haskell.org/package/ekg-0.4.0.15/docs/System-Remote-Label.html#t:Label) to [Gauges](http://hackage.haskell.org/package/ekg-0.4.0.15/docs/System-Remote-Gauge.html#t:Gauge) where possible.
