### ISSUE TITLE
E8.1 specification of benchmarks

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#366]
@njd42 ideas:

* dividend paying to stakeholders (1 source address, n target addresses; where n can be very large e.g. 10^6)

**Comment by njd42** [comment]
The aim (eventually) here is a benchmark that anyone can take and tryout themselves (e.g by deploying it on real machines in real locations) themselves. With that in mind it gives a set of (eventual) requirements - initially those requirements would be 'touchstones' to ensure we don't cut off / make expensive because of rewriting this future.
